data:
  dataset_name: att_sicapv2_binary
  input_path: ./input/sicapv2_binary/feature_predictions/
  train_file: Train.csv
  val_file: Val.csv
  test_file: Test.csv
  wsi_file: wsi_labels.csv
  output_path: ./out/

  num_classes: 2
  type: binary # binary, prostate_cancer
  cut_bags: True

