data:
  dataset_config: ./dataset_dependent/sicapv2/dataset_config.yaml
  artifact_dir: ./out

  col_feature_prefix: 'feature'
  col_instance_label: 'instance_label'
  col_cnn_prediction: 'cnn_prediction'
  col_bag_label: 'bag_label'
  col_bag_name: 'bag_name'
  col_bag_cnn_prediction: 'bag_cnn_prediction'
  col_bag_cnn_probability: 'bag_cnn_probability'

model:
  attention: gp # deterministic, gp
  hidden_layer_size: 128
  inducing_points: 64
  optimizer: adam
  learning_rate: 0.0001
  epochs: 200
  prior: 0.0
  kl_factor: 1.0
  metrics_for_model_saving: val_categorical_accuracy
  load_model: None # 'None' or path to experiment folder which containes 'models' directory with .h5 files
  save_model: True # True or False

logging:
  log_artifacts: False
  run_name: default
  tracking_url: ./mlruns #/home/arne/projects/mlruns