path_train_df: ./input/cam16/feature_predictions/Train.csv
path_val_df: ./input/cam16/feature_predictions/Val.csv
path_test_df: ./input/cam16/feature_predictions/Test.csv
path_wsi_df: ./input/cam16/feature_predictions/wsi_labels.csv
output_path: ./out/

# input column naming convention
col_feature_prefix: 'feature'
col_instance_label: 'instance_label'
col_cnn_prediction: 'cnn_prediction'
col_bag_label: 'bag_label'
col_bag_name: 'bag_name'
col_bag_cnn_prediction: 'bag_cnn_prediction'
col_bag_cnn_probability: 'bag_cnn_probability'