data:
  dataset_config: ./dataset_dependent/sicapv2/dataset_config.yaml
  artifact_dir: ./out

  col_feature_prefix: 'feature'
  col_instance_label: 'instance_label'
  col_cnn_prediction: 'cnn_prediction'
  col_bag_label: 'bag_label'
  col_bag_name: 'bag_name'
  col_bag_cnn_prediction: 'bag_cnn_prediction'
  col_bag_cnn_probability: 'bag_cnn_probability'

model:
  attention: baseline_mean # deterministic, gp, deterministic_gated, baseline_mean
  class_weighted_loss: False
  hidden_layer_size_0: 128
  hidden_layer_size_1: 128
  hidden_layer_size_2: 64
  hidden_layer_size_att: 0
  hidden_layer_act_att: relu
  att_sigmoid: False
  inducing_points: 64
  optimizer: adam
  learning_rate: 0.001
  lr_decay_after_epoch: 10
  lr_decay_factor: -0.1
  epochs: 20
  prior: 0.0
  kl_factor: 1.0
  metrics_for_model_saving: None # val_categorical_accuracy or None
  load_model: False # 'None' or path to experiment folder which containes 'models' directory with .h5 files
  save_model: True # True or False

logging:
  log_artifacts: False
  save_predictions: True
  run_name: default # 'auto' to automatically take the folder name
  tracking_url: ./mlruns #/home/arne/projects/mlruns