data:
  dataset_name: att_cam16
  input_path: ./input/cam16/feature_predictions_128/
  train_file: Train.csv
  val_file: Val.csv
  test_file: Test.csv
  wsi_file: wsi_labels.csv

  num_classes: 2
  type: binary # binary, prostate_cancer
  cut_bags: True


